/**
 * Centralized Looter Game Configuration
 */

export const GAME_CONFIG = {
  // Navigation & Interaction
  FORTRESS_INTERACTION_METERS: 250,
  PICKUP_INTERACTION_METERS: 150,
  PORTAL_SPACING_METERS: 5000,
  PORTAL_SEARCH_RADIUS: 3,

  // UI & UX
  SYNC_HEARTBEAT_MS: 30000,
  NOTIFY_DURATION_MS: 3000,

  // Inventory Scaling (Grid sizes)
  GRID_MIN_W: 4,
  GRID_MIN_H: 4,
  GRID_MAX_W: 7,
  GRID_MAX_H: 6,

  // Combat & Balancing
  BASE_HP: 100,
  COMBAT_BOAT_SCALE_MULTIPLIER: 3,
  COMBAT_ENEMY_BOAT_OFFSET_PX: 120,
  COMBAT_MIDPOINT_OFFSET_PX: 60,
  CURSE_GAIN_MOVE_BASE: 0.1, // % per meter
  CURSE_GAIN_PICKUP: 5,     // % flat
  CURSE_GAIN_MINIGAME_LOSE: 15, // % flat

  // Tiers
  TIER_MAX: 5,
  TIER_COSTS: [0, 10, 100, 1000, 10000, 100000],

  // Spawn
  SPAWN_MIN_DISTANCE_FROM_FORTRESS: 1500,
  SPAWN_MIN_ITEM_SPACING: 2000,
  SPAWN_MAX_ITEM_SPACING: 5000,
  SPAWN_RING_RADIUS: 10000,
  CHUNK_FETCH_RADIUS: 10,

  // Proximity spawn
  PROXIMITY_SPAWN_RADIUS: 5000,
  PROXIMITY_INITIAL_COUNT: 8,
  PROXIMITY_MILESTONE_COUNT: 4,
  PROXIMITY_MILESTONE_METERS: 500,
};

export default GAME_CONFIG;
